import { Providers } from './providers'
import '../styles/globals.css'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <main className="h-screen flex flex-col justify-center items-center">
                    <Providers>{children}</Providers>
                </main>
            </body>
        </html>
    )
}
